### PR TITLE
wiringPiISR and waitForInterrupt are changed.

### PR DESCRIPTION
**Pull request by nopnop2002**
GPIO of OPI don't have interrupt function.
poll function don't work.
So read periodically /sys/class/gpio_sw/XXX/data.(/sys/class/gpio_sw/PA1/data)
And change is judged.

### CODE REVIEW

**Comment by sercxjo** [comment]
GPIO has interrups in other driver enabled in Armbian. It works with the WereCatf's fork.

**Comment by nopnop2002** [comment]
I tried this code using WereCatf's fork.
But even if a button was pressed, an event didn't occur.
Is an additional driver somewhat necessary?

`#include <wiringPi.h>
#include <stdlib.h>
#include <stdio.h>

#define pin     0

void signal(void){
  printf("Signal\n");
}

int main(void){
  if(wiringPiSetup() == -1) {
    printf("wiringPiSetup Error\n");
  }
  pinMode(pin,INPUT);
  wiringPiISR(pin, INT_EDGE_FALLING, signal );
//  wiringPiISR(pin, INT_EDGE_RISING, signal );
  while(1) {
    sleep(10000);
  }
  return 0;
}
`

**Comment by sercxjo** [comment]
WereCatf's fork based on old version, I have merged it with the current fork, better see [it](https://github.com/sercxjo/WiringOP).
1. Interrupts works only with PA... and PG... pins.
2. I use Ubuntu with [recompiled kernel](https://github.com/sercxjo/OrangePI-Kernel).
   Check that directory `/sys/class/gpio/` is presented.

My example with button between pin 37 (PA20) and pin 39 (Ground):

```
#define DBTN 37
wiringPiSetupPhys();
pinMode(DBTN, INPUT);
pullUpDnControl(DBTN, PUD_UP);
wiringPiISR(DBTN, INT_EDGE_BOTH, &btn_interrupt) ;
```

**Comment by nopnop2002** [comment]
Hello sercxjo.
Would your fork also work in Armbian?
Is recompiled kernel needed?

**Comment by sercxjo** [comment]
I have not tried Armbian. [Here](http://forum.armbian.com/index.php/topic/2070-how-orangepi-interrupt-works/) is written that it works. I just ported kernel config-file from the last version of Armbian. Just add `CONFIG_GPIO_SYSFS=y` to the config.

**Review by zhaolei — COMMENTED** [review]
ok

**Pull request closed without merging**
